### ISSUE TITLE
Configure for VoIP

### ISSUE THREAD

**Issue by miken01** [twilio/voice-quickstart-server-python#11]
I am currently working with this quickstart along with the voice-quickstart-swift quickstart. My end goal is to implement VoIP calling. My question is how would I configure this server to connect a VoIP call between two clients? 

I believe I am following the Swift quickstart about as completely as I can and have made sure to use the portion of the quick start that is related directly with VoIP. As far as I can tell it's working, but when I place a call I get the stock "Congratulations! You have made your first oubound call! Good bye.". Due to this I believe there is something I need todo within the `outgoing` method, but not sure what todo in order to connect two clients via VoIP.

I have tried the TwilML `call` command, but this seems to generate an actual phone call to a user's phone number. What I'm looking for is a way to perform a VoIP call that would then utilize Apple's VoIP push notification to alert the user of an incoming call.

Any help here would be greatly appreciated. I appreciate that this is sort of a combination between two quickstarts, but right now I think the server is the side that needs to be updated.

Thanks!

**Comment by bchen-twilio** [comment]
Hi @miken01 

Thanks for choosing the Voice iOS SDK and don't worry, you are just one step (or may 2 more :p) away from your goal of making calls between (mobile) clients.
Could you please check out the discussion in this thread (https://github.com/twilio/voice-callkit-quickstart-objc/issues/6)? Basically what you'll have to do is to 
1. make your server to dynamically return access tokens with different identities, which are provided by the iOS application via the HTTP request to the server endpoint
2. in the `/placeCall` endpoint, extract the parameters (for example "to" and "from") and use the TwiML response library to dial to another client.

Please free feel to let us know if you need any help with this.

Cheers,
-bobie

**Comment by miken01** [comment]
Hi Bobby,

Thanks for the help with this. What you said makes sense, and in the quickstart for python the /placecall endpoint looks to already have the logic you speak of except for that it's using the python client instead of the TwilML dial response (see below). With this I have a couple of questions.

1. Doesn't the TwiML dial command place an actual call to a phone number or is it also used for VoIP?

2. I understand the identity can be anything, but when sending through the "to" and "from" client identifiers what should these be? Would the "from" be the identity I created on the recipient end? If that's the case does it make sense to generate an identity for each user and maintain it for the life of the application and reuse it?

3. By default the voice-quickstart-swift hits the /outgoing endpoint per the setup instructions here, and I believe that is because it's defined within the TwilML App settings within the console. Instead of using the /outgoing endpoint should I update this to just use the /placeCall endpoint?

Sorry for all the questions here. I'm just doing my best to understand the SDK and all. It's massive and does so much it's hard to take it all in.

Here is the code snippet from my implementation the /placeCall endpoint.

```
@app.route('/placeCall', methods=['GET', 'POST'])
def placeCall():
  account_sid = os.environ.get("ACCOUNT_SID", ACCOUNT_SID)
  api_key = os.environ.get("API_KEY", API_KEY)
  api_key_secret = os.environ.get("API_KEY_SECRET", API_KEY_SECRET)

  client = Client(api_key, api_key_secret, account_sid)
  call = client.calls.create(url=request.url_root + 'incoming', to='client:' + IDENTITY, from_='client:' + CALLER_ID)
  return str(call.sid)
```

**Comment by bchen-twilio** [comment]
Hey @miken01 

1. The Dial verb is one of the most powerful and fundamental function of Twilio. In the python quickstart `/placeCall`, we added the `url=` so that once the receiver accepts the call Twilio will send out another HTTP request to this URL, just to demonstrate a quickstart example. More documentation for the [Dial verb](https://www.twilio.com/docs/api/twiml/dial).

2. Your endpoint is powerful and can do anything, using the name of the "call receiver" is just one of the things you can do. In the Programmable Voice SDK world, yes the identity is actually used for the VoIP push service registration and will stick to the application+device unless you explicitly unregister.

3. Yes, you need to go to the Programmable Voice console and update your [TwiML app](https://www.twilio.com/console/voice/dev-tools/twiml-apps) with the request URL you want.

Don't worry. We've all been there and totally understand the steep learning curve. Let's try this in you python endpoint:

```
def placeCall():
    resp = twiml.Response()
    toClient = request.values.get('FROM_APP_TO', '')
    if toClient[0] in "+1234567890":
        resp.dial(callerId='CALLER_ID).number(toClient)
    elif len(toClient) > 0:
        resp.dial(callerId='CALLER_ID').client(toClient)

    return resp
```

Note that in the server endpoint I am trying to extract the `FROM_APP_TO` parameter (which means "this is from the app and I want to dial to...") and use it as the identity of whom I am dialing to connect. In you iOS app:

```
    [[VoiceClient sharedInstance] call:self.accessToken
                                params:@{@"FROM_APP_TO", @"voice_test"}
                              delegate:self];
```

Use the `params` and put a dictionary with `FROM_APP_TO` as the key and `voice_test` as the value. Once Twilio receives your call from the mobile app, it will pass whatever you have in the `params` to the request URL specified in you TwiML app (app-SID). Again, `FOM_APP_TO` and `voice_test` can be anything.

**Comment by miken01** [comment]
Hi,

Thanks again for the great info. I've been able to setup a test and make some adjustments. Everything seems to be working correctly on the calling end. Meaning when I tap to place a VoIP call it connects and I hear it ringing. However, the recipient device is never sent any notification for an incoming call.

One thing I find strange is when I look in my Twilio dashboard I see that this process generates two calls. One is an incoming call from my calling device (voice_test_1), and the second is an outgoing call to my recipient device (voice_test_2). The thing that is really strange about this on the outgoing call it says it's from the number (864) 238-3781. Is this normal? Please see attach screenshot.

![screen shot 2017-03-23 at 3 37 54 pm](https://cloud.githubusercontent.com/assets/2405488/24266871/b808b1e8-0fde-11e7-9c2a-8b83eb5204d3.png)

I just want to make sure I'm doing this right on the server side. I am pretty sure the client is correct as I'm using your own test codebase, so hopefully that should be fully working :)

Anyways, here is my /outgoing endpoint code. I decided to use that one for now so I didn't have to modify my TwilML App. Later I'll add this code to the /placecall endpoint.

```
@app.route('/outgoing', methods=['GET', 'POST'])
def outgoing():

  resp = twilio.twiml.Response()
  with resp.dial(callerId='voice_test_1') as r:
    r.client('voice_test_2')

  return str(resp)
```

Also, this is the code I have to generate the access token. I have made it generic, and have created builds on each device with a hard coded identity mentioned above.

```
@app.route('/accessToken')
def token():
  account_sid = os.environ.get("ACCOUNT_SID", ACCOUNT_SID)
  api_key = os.environ.get("API_KEY", API_KEY)
  api_key_secret = os.environ.get("API_KEY_SECRET", API_KEY_SECRET)
  push_credential_sid = os.environ.get("PUSH_CREDENTIAL_SID", PUSH_CREDENTIAL_SID)
  app_sid = os.environ.get("APP_SID", APP_SID)

  clientId = request.values.get('client_id', '')

  grant = VoiceGrant(
    push_credential_sid=push_credential_sid,
    outgoing_application_sid=app_sid
  )

  token = AccessToken(account_sid, api_key, api_key_secret, clientId)
  token.add_grant(grant)

  return str(token)
```

My last question is will the recipient not receive any notification of an incoming call if there is an issue with the Apple VoIP certificates? I know for while the app is in the background or terminated that would cause an issue, but what about when the app is open?

Thanks!

**Comment by bchen-twilio** [comment]
Hi @miken01 

The calling part you are seeing is perfectly good and that's how Twilio works.
Now let's move on to the next frustration - push notification setup.

Before I ask you to provide us the Twilio Account SID and your Push Credential SID (CR***), could you help us check a few things?
- you are using a VoIP Service certificate and the CSR (certificate signing request) file is never used for creating any APNS certificate before.
- and yes, it has to be VoIP Service certificate, not APNS certificate.
- when creating the Push Credential in the console, make sure you have select the "sandbox" option according to the .entitlements file in the app project. "sandbox" works with "APS Environment: development". You'll need another Push Credential without "sandbox" and update the entitlements with "APS Environment: production" when your app is ready for store submission.

You account SID and Push Credential SID will definitely help us dig up more details. Please don't share any other credentials here ;)

**Comment by miken01** [comment]
Ok, your steps helped me solve the problem I was having. I think the issue was that I had my production APNS certificate installed on my AWS SNS instance, and then I was trying to use a Sandbox VoIP cert through your service. When I updated everything to run against the Apple Sandbox things started to work correctly.

Thanks for the help!

**Comment by bchen-twilio** [comment]
Glad that it's working now Mike!
I am going to close this ticket for now but please feel free to reopen or create new issues if you run into any in the future.

**Comment by krishanjangir** [comment]
I have done the same but push message is the only issue i am facing.
In my PHP server there is nothing to add CR*** identity, could you please provide me the PHP server code to generate token having this CR*** identity.
I am following below PHP code to generate token for voice.
https://www.twilio.com/docs/api/rest/access-tokens.

You can see there is no code for "push_credential_sid" as like python server code.

**Comment by bchen-twilio** [comment]
Hi @krishanjangir 

Thanks for writing in.
Sorry that the example on the website doesn't show all the parameters. There is a `pushCredentialSid` property in the Twilio PHP `VoiceGrant` object. Could you please give it a try?

-bobie

**Comment by gmchandarana** [comment]
Hii @miken01 , can you provide some code? I'm having the same issue and can't figure out how to solve it

**Comment by krishanjangir** [comment]
Hi Gaurav,

Yes man I can provide you code.
Pls WhatsApp me on Monday.

9413545237



On 02-Nov-2017 3:00 PM, "Gaurav Chandarana" <notifications@github.com>
wrote:

Hii @miken01 <https://github.com/miken01> , can you provide some code? I'm
having the same issue and can't figure out how to solve it

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/twilio/voice-quickstart-server-python/issues/11#issuecomment-341364583>,
or mute the thread

**Comment by girtis** [comment]
Hi all,

In PHP there is a `setPushCredentialSid()` [method](https://github.com/twilio/twilio-php/blob/bd0ce5e1d81d0b872a39e96d637b9ed4c63e36e5/Twilio/Jwt/Grants/VoiceGrant.php#L78) which you can use to set the credential.

The resulting code would be something like
```
$voiceGrant->setPushCredentialSid($pushCredentialSid);
```

Thanks,


Girts

**Comment by uriel-frankel** [comment]
I tried the Android quickstart and I succeeded to hear the message. But how can I establish a voip call from one device to other? I can't find a docs to explain it. This is very frustrating.
