### ISSUE TITLE
Failing to deploy on Heroku 

### ISSUE THREAD

**Issue by markmacau** [twilio/voice-quickstart-server-python#19]
Heroku stops with following error. It seems a simple bug but I have no idea for python. Thanks, 

```
print "Setuptools version",version,"or greater has been installed."
                                        ^
           SyntaxError: Missing parentheses in call to 'print'
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ehff5rff/wsgiref/
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by bchen-twilio** [comment]
Hi @markmacau 

Sorry you are experiencing problem deploying the server app to Heroku.
Could you please remove the `wsgiref` line in `requirements.txt` and try deploying again?

Thanks.

**Comment by AudyOdi** [comment]
Hi @bchen-twilio 

I get the same error as @markmacau described and I want to confirm that your solution for removing `wsgiref` from `requirements.txt` is working. Can I submit a PR for this? Thanks!

**Comment by bchen-twilio** [comment]
Hi @AudyOdi 

I've just merged [the PR](https://github.com/twilio/voice-quickstart-server-python/pull/20) to specify python runtime version for Heroku.
Could you pull the latest and try again if Heroku deployment works for you?
Thanks!

-bobie

**Comment by bchen-twilio** [comment]
Closing this issue assuming the `runtime.txt` update fixed the problem.
