### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by aminra96** [twilio/voice-quickstart-server-python#22]
hello,
I have changed the server a little bit, i have mixed it up with the one for twilio client
but i can not recieve inbound calls, I have looked into my logs and I saw this Error : rdtnotification invalid apns device token.
thank you

**Comment by bchen-twilio** [comment]
Hi @aminra96 

Bobie from the SDK team. Thank you for choosing the Twilio SDK.
Can you provide us the access token you use in your mobile app for registration? you know where to find my email. (please don't post any of your credentials here)
Once I have your account credentials from the access token, I can dig into the DB and check if there is anything wrong that caused notification delivery failure.

It would also be great if you could check out the [iOS Voice SDK FAQ](https://www.twilio.com/docs/api/voice-sdk/ios/faq) and hopefully there is some helpful answer to the issue you are experiencing.

Thanks.
-bobie

**Comment by aminra96** [comment]
Hi @bchen-twilio,
i would provide the accessToken as fast as i can access to the twilio account.
I have made an apple push notification certification, but no voip certificate, would it make a problem?

regards
amin

**Comment by bchen-twilio** [comment]
Hi @aminra96 

Actually you will need a VoIP Service certificate to make incoming call push notification work for the Programmable Voice iOS SDK. The Twilio Notify service sends the notification requests specifically to the VoIP Service so if the certificate used for create Push Credential is not a VoIP certificate, the "invalid apns device token" message will be logged.

Another thing to keep in mind is to use a fresh CSR (certificate signing request) file when creating the VoIP Service cert. Using a CSR file that was used for creating regular APNS certificate will also cause the SDK trouble of sending push notifications.

Let me know if this helps.

Thanks
-bobie

**Comment by aminra96** [comment]
Hi @bchen-twilio 
I have used  a fresh CSR file and created voip certificate, but still it's not working, the same error in debuger :(
Thanks,
Amin

**Comment by aminra96** [comment]
Hi again,
@bchen-twilio 
This issue was from that xcode made a distribution provisioning profile and my app was not supposed to be a distribution app, I had manually made a development provisioning profile and now I am able to receive push notifications and incoming calls.
Thanks for the support, I think i should close this issue.
Amin

**Comment by bchen-twilio** [comment]
That's great @aminra96!
Let us know if you run into any issue in the future.
Looking forward to your awesome Voice app.

-bobie
