### ISSUE TITLE
No module named jwt.access_token

### ISSUE THREAD

**Issue by kalyanpkumar** [twilio/voice-quickstart-server-python#26]
When i tried to run python server.py, i get the following error

Traceback (most recent call last):
  File "server.py", line 3, in <module>
    from twilio.jwt.access_token import AccessToken
ImportError: No module named twilio.jwt.access_token

i have my requirements.txt as follows

Flask==0.10.1
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.9.6
httplib2==0.9
itsdangerous==0.24
six==1.*
twilio==6.10.0
wsgiref==0.1.2

**Comment by idelgado** [comment]
Please rerun `pip install -r requirements.txt`

**Comment by idelgado** [comment]
Let us know if this did not solve your problem. Thanks
